OCPBUGS-57320: Skip TestAWSLBControllerWIthWAFRegional (WAF Classic) test
TestAWSLoadBalancerControllerWithWAFRegional was permafailing with
the following message on the attempt to create aws waf regional acl:
WAFBadRequestException: AWS WAF Classic (v1) support will end on September 30, 2025.
Effective May 1st, 2025, the creation of new WebACL v1 is no longer permitted.

This PR introduces a skip for TestAWSLoadBalancerControllerWithWAFRegional
until we deprecate WAF Classic addon in ALBO API